//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseMgmtSvc
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DatabaseMgmtSvc.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setNew", ReplyAction="http://tempuri.org/IService/setNewResponse")]
        bool setNew(double temp, double hum, double CO2, double lux, double db, double motion, string room_ref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setNew", ReplyAction="http://tempuri.org/IService/setNewResponse")]
        System.Threading.Tasks.Task<bool> setNewAsync(double temp, double hum, double CO2, double lux, double db, double motion, string room_ref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getDataRow", ReplyAction="http://tempuri.org/IService/getDataRowResponse")]
        string getDataRow(int row, string room_ref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getDataRow", ReplyAction="http://tempuri.org/IService/getDataRowResponse")]
        System.Threading.Tasks.Task<string> getDataRowAsync(int row, string room_ref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getDataColumn", ReplyAction="http://tempuri.org/IService/getDataColumnResponse")]
        string getDataColumn(string param, string room_ref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getDataColumn", ReplyAction="http://tempuri.org/IService/getDataColumnResponse")]
        System.Threading.Tasks.Task<string> getDataColumnAsync(string param, string room_ref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getDataCell", ReplyAction="http://tempuri.org/IService/getDataCellResponse")]
        string getDataCell(int row, string param, string room_ref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getDataCell", ReplyAction="http://tempuri.org/IService/getDataCellResponse")]
        System.Threading.Tasks.Task<string> getDataCellAsync(int row, string param, string room_ref);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceChannel : DatabaseMgmtSvc.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<DatabaseMgmtSvc.IService>, DatabaseMgmtSvc.IService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool setNew(double temp, double hum, double CO2, double lux, double db, double motion, string room_ref)
        {
            return base.Channel.setNew(temp, hum, CO2, lux, db, motion, room_ref);
        }
        
        public System.Threading.Tasks.Task<bool> setNewAsync(double temp, double hum, double CO2, double lux, double db, double motion, string room_ref)
        {
            return base.Channel.setNewAsync(temp, hum, CO2, lux, db, motion, room_ref);
        }
        
        public string getDataRow(int row, string room_ref)
        {
            return base.Channel.getDataRow(row, room_ref);
        }
        
        public System.Threading.Tasks.Task<string> getDataRowAsync(int row, string room_ref)
        {
            return base.Channel.getDataRowAsync(row, room_ref);
        }
        
        public string getDataColumn(string param, string room_ref)
        {
            return base.Channel.getDataColumn(param, room_ref);
        }
        
        public System.Threading.Tasks.Task<string> getDataColumnAsync(string param, string room_ref)
        {
            return base.Channel.getDataColumnAsync(param, room_ref);
        }
        
        public string getDataCell(int row, string param, string room_ref)
        {
            return base.Channel.getDataCell(row, param, room_ref);
        }
        
        public System.Threading.Tasks.Task<string> getDataCellAsync(int row, string param, string room_ref)
        {
            return base.Channel.getDataCellAsync(row, param, room_ref);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:25253/DB_USAGE_SVC/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
